# config/routes.yaml

# the "app_lucky_number" route name is not important yet
#app_lucky_number:
#   path: /lucky/number
#   controller: App\Controller\LuckyController::number
# config/routes.yaml

homepage:
    path: /home
    controller: App\Controller\HomeController::home
addProduct:
    path: /add
    controller: App\Controller\ProductController::addProduct
deleteProduct:
    path: /deleteProduct
    controller: App\Controller\ProductController::deleteProduct
manageClient:
    path: /manageClient
    controller: App\Controller\ClientController::manageClient
sendProduct:
    path: /sendproduct/{product_id}
    controller: App\Controller\ProductController::sendProduct
saveCommand:
    path: /saveCommand
    controller: App\Controller\CommandController::saveCommand
addClient:
    path: /addClient
    controller: App\Controller\ClientController::addClient
addCommand:
    path: /addCommand
    controller: App\Controller\CommandController::addCommand
displayAllOrders:
    path: /displayAll
    controller: App\Controller\CommandController::displayAllOrders
deleteAllCommand:
    path: /deleteAllCommand
    controller: App\Controller\CommandController::deleteAllCommand